package corba;

/**
* corba/EchoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* lunes 11 de noviembre de 2019 01:39:50 PM GMT
*/

public final class EchoHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Echo value = null;

  public EchoHolder ()
  {
  }

  public EchoHolder (corba.Echo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.EchoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.EchoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.EchoHelper.type ();
  }

}
