package corba;


/**
* corba/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* lunes 11 de noviembre de 2019 01:39:50 PM GMT
*/

public interface EchoOperations 
{

  // Methods
  String echoService (String input);
} // interface EchoOperations
