/*
 *  EchoServerImpl.java
 *  Template to build a CORBA object implementation.
 *  Please replace the string MYCORBAOBJECT with the name of your object following
 *  the instructions detailed in the code comments.
 *
 *  @author Jose Simo. (c) ai2-DISCA-UPV Creative Commons.
 *
 *  Rev: 2017
 */

package server;
/**
 * This class is the implementation object for your IDL interface.
 *
 * Let the Eclipse complete operations code by choosing 'Add unimplemented methods'.
 */
///////////Template customization:
// Set the name of the class and extends from your object POA
// (Replace MYCORBAOBJECT with the name of your object).
// Check the POA name: See the code generated by idlj when proccesing your idl file.

public class EchoServerImpl extends corba.EchoPOA {
	/**
	 * Constructor for EchoServerImpl
	 */
	EchoObject echo = new EchoObject();
	public EchoServerImpl() {
	}

	@Override
	public String echoService(String input) {
		// TODO Auto-generated method stub
		return echo.echo(input);
	}
	
	

}
