package corba.camara;


/**
* corba/camara/CamaraInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* martes 12 de noviembre de 2019 06:51:36 PM GMT
*/

public interface CamaraInt extends CamaraIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CamaraInt
