package corba.camara;


/**
* corba/camara/CamaraIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* viernes 29 de noviembre de 2019 08:16:14 PM GMT
*/

public interface CamaraIntOperations 
{
  corba.camara.suscripcionD SuscribirRobot (String IORrob);
} // interface CamaraIntOperations
