package corba.robot;


/**
* corba/robot/RobotSeguidorIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* martes 12 de noviembre de 2019 06:51:35 PM GMT
*/

public interface RobotSeguidorIntOperations 
{
  void ObtenerEstado (corba.instantanea.EstadoRobotDHolder est);
} // interface RobotSeguidorIntOperations
