package corba.instantanea;


/**
* corba/instantanea/InstantaneaD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* martes 12 de noviembre de 2019 06:51:36 PM GMT
*/

public final class InstantaneaD implements org.omg.CORBA.portable.IDLEntity
{
  public corba.instantanea.EstadoRobotD estadorobs[] = null;

  public InstantaneaD ()
  {
  } // ctor

  public InstantaneaD (corba.instantanea.EstadoRobotD[] _estadorobs)
  {
    estadorobs = _estadorobs;
  } // ctor

} // class InstantaneaD
